version: 2.1
jobs:
  build-and-test-compiler:
    docker:
      - image: silkeh/clang
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
workflows:
  build-and-test-compiler-workflow:
    jobs:
      - build-and-test-compiler
